### ISSUE TITLE
Exporter errors cause pod to Crashloop

### ISSUE THREAD

**Issue by chris-sanders** [MqllR/storj-storagenode-chart#5]
Errors like https://github.com/anclrii/Storj-Exporter/issues/57 cause the whole pod to go into a crashloop. 

I think this is preventing the node from being online just because the exporter has an issue. Can the exporter be broken out into it's own pod so the uptime of the node is not impacted by the availability of the exporter, or am I misunderstanding the impact here?

**Comment by MqllR** [comment]
Hello @chris-sanders!

Did you try to use the latest release of the Storj exporter? I tried quickly locally and it fix the issue.

If you want to override the default image name, add this argument to your helm install command:

```
--set metrics.image.repository=docker.io/anclrii/storj-exporter:1.0.10
```

I'll publish a new chart release with this fix.

**Comment by chris-sanders** [comment]
I did, I was using 
anclrii/storj-exporter:1.0.12@sha256:9efda7c03cf88904456a004b85322907b3e81167647e2ba659aab1ad5840421c

Even with this revision the error was present. Notice that it only happens on the 1st, so testing today should work fine.

I eventually disabled metrics in the chart, which doesn't install the exporter container in the pod and allowed it to run on the 1st of the month.
