### ISSUE TITLE
Ingress error on k3s v1.22.7+k3s1

### ISSUE THREAD

**Issue by tolkonepiu** [MqllR/storj-storagenode-chart#8]
I am getting this error after enabling ingress in chart:
```
Helm install failed: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Ingress" in version "networking.k8s.io/v1beta1"
```

**Comment by MqllR** [comment]
Hi @tolkonepiu,

Thank you for bringing up the issue. Indeed, the semver detection in the ingress template was out of date. I've just refreshed the template and this should be fixed in the release `0.3.1`.
